import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/navbar/navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Navbar />
          {/* Add pt-16 to push content below the fixed navbar */}
          <main className="pt-20">
            {children}
          </main>
      </body>
    </html>
  );
}
