services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web-app
    hostname: web-app
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent host from overwriting node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development

  api:
    build: ./api
    container_name: web-api
    hostname: web-api
    volumes: ["./api:/apicode"]
    ports:
      - 4000:4000

  db:
    env_file:
      - ./api/.env
    image: mysql:9
    container_name: mysql_db
    hostname: db
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3200:3306
